#!/usr/bin/env bash

# Note: This is also used for Scanner.

set -euo pipefail

[ -d /.init-dirs ] || exit 0

# Use --no-clobber to make this operation idempotent. This is necessary because
# sensor calls this script twice, and some files lack write permissions (making
# --force ineffective). The --no-clobber flag ensures the script can be safely
# called multiple times without errors, assuming the directories are configured
# correctly in the first place.
cp --recursive --no-dereference --no-clobber /.init-dirs/* /
